### PR TITLE
[ocaml] Fix ocamlopt options for linker to use -cclib w/ new OCaml

### PR DESCRIPTION
**Pull request by rossphilipson**
OXT-698

Signed-off-by: Ross Philipson <philipsonr@ainfosec.com>

### CODE REVIEW

**Comment by rossphilipson** [comment]
Custom build here:
http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/637
Goes with:
https://github.com/OpenXT/xenclient-oe/pull/554

**Comment by rossphilipson** [comment]
Rebased, building here:
http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/649

**Comment by eric-ch** [comment]
LGTM, smoke test passed. Will merge soon.

**Comment by eric-ch** [comment]
Tested again in (build 654)[http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/654].
LGTM, merging.

**Pull request merged**
