### PR TITLE
Remove xenops and xenvm

### PR DESCRIPTION
**Pull request by jean-edouard**
OXT-916

Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by crogers1** [comment]
Did anything break when you nuked these out of dom0?  I wouldn't be surprised if there was some random script or something calling one of them directly

**Comment by jean-edouard** [comment]
Good point, I didn't do a full build with that PR, we should try a custom build make sure everything is happy.

**Comment by stacktrust** [comment]
A JIRA ticket for this change would help with tracking unforeseen consequences.

**Comment by jean-edouard** [comment]
OXT-916

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/566

**Comment by jean-edouard** [comment]
Yup, breaks stuffs, do not merge!

**Comment by jean-edouard** [comment]
We're a lonnnng way from being able to do this...
Closing for now...

**Comment by jean-edouard** [comment]
Reopening to test with the other PRs

**Comment by jean-edouard** [comment]
This PR goes with:
https://github.com/OpenXT/manager/pull/55
https://github.com/OpenXT/network/pull/4
https://github.com/OpenXT/xenclient-oe/pull/524
https://github.com/OpenXT/xenclient-oe/pull/525
https://github.com/OpenXT/xenclient-oe/pull/529

It should be ready for testing now.

**Comment by rossphilipson** [comment]
Doing a build since the last one was missing 529.

**Comment by rossphilipson** [comment]
Build here (testing now):
http://openxt.ainfosec.com/builds/custom/master/584

**Pull request merged**
